# Generated by Django 5.0.4 on 2024-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
