# Generated by Django 5.0.4 on 2024-06-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_link_project_app_link_project_github_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True)),
                ('app_link', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(related_name='dproject', to='portfolio.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DataProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dproject_images/')),
                ('dproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimages', to='portfolio.dataproject')),
            ],
        ),
    ]
