# Generated by Django 5.0.4 on 2024-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_datatag_dataproject_dataprojectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='tags',
            field=models.ManyToManyField(related_name='dproject', to='portfolio.datatag'),
        ),
    ]
